sudo: required
services:
  - docker

before_install:
  - docker build -t aferracci/docker-react -f Dockerfile.dev .

script:
  - docker run aferracci/docker-react npm run test -- --coverage

# Necessary to deploy on AWS env
#deploy:
#  provider: elasticbeanstalk
#  region: ""
#  app: "docker"
#  env: "Docker-env"
#  bucket_name: ""
#  bucket_path: "docker"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY 